### ISSUE TITLE
add the static list of podcasts

### ISSUE THREAD

**Issue by godsakani** [osscameroon/podcasts#12]
Currently there's no list of podacast. add a static podcast List that displays the different types of podcast available.
How to go about it:
1) Create a podcastList.js file in a react component call podcast
2) Create a podcastList.css file in a react component call podcast for styling 
3) Create a react component call track which is made up of array of object in a file call track.js which store the details of podcast in form of array of subject. that is Podcast id, podcast title, podcast Name, podcast mp3. 
4) import the track.js and used in podcastList.js
5) import the podcastList to app.js for render
6) run your app

**Comment by Sanix-Darker** [comment]
Closing this since @godsakani already implemented it !
