### ISSUE TITLE
Add static sort button next to the search bar

### ISSUE THREAD

**Issue by yokwejuste** [osscameroon/podcasts#13]
## Description
added a static sort button next to the search bar. this sort button helps sort the podcast list . being static means it has no functionality. just the design and js file

## how I will code it
Create a sortButton component and add two files
Two files needed we have the sortButton.js and sortButton.css file
The sortButton.js file for implementing the function 
The sortButton.css file for the styles

**Comment by godsakani** [comment]
Ok @Sanix-Darker  am on it

**Comment by godsakani** [comment]
Hello @Sanix-Darker 
 should the sort be done base on the date it was updated or it should base on ascending or descending order

**Comment by Sanix-Darker** [comment]
The default sort should be based on the date !
