### ISSUE TITLE
Make the search bar dynamic (means making it work)

### ISSUE THREAD

**Issue by godsakani** [osscameroon/podcasts#17]
The search bar is static is not functional that is is unable to filter and search podcast from podcast list. making the search dynamic means it should be able to search and filter the podcast list base on User input.

How to go about it:
1) Create React searchForm.js function component file
2) Register or store result of searchForm.js In React
3) Start React Server

Tips:
Make  use of the filter() and startsWith() methods (just two Javascript methods) to find out Podcast  whose search matches the text entered in the search box. We also use the toLowerCase() method to make it case insensitive.

this link will help:
https://www.kindacode.com/article/how-to-create-a-filter-search-list-in-react/

Sample example below:

![Search](https://user-images.githubusercontent.com/70459251/165110338-fbb50a81-a2bd-4ddd-90c7-6e91b663ff2c.png)

**Comment by godsakani** [comment]
Hello @yokwejuste , @Sanix-Darker 
Good day. trust we are doing well.
I was working on the corrections @yokwejuste  gave gave on this PR I opened days ago. I finally adjusted styles back.
But currently facing some issues with search functionality. 

I have issues on how to call the search function in to the podcastslist.
The is not functioning below are the screens of the outputs:

1. No results after refactoring the code :
![no result](https://user-images.githubusercontent.com/70459251/165806546-824f1c6a-2b05-40c8-9057-61ec037a4dec.png)

2. Trying calling the function the way I understood but gives error messages:
![err](https://user-images.githubusercontent.com/70459251/165807634-f6880165-1af8-49af-bd68-a8e451781ae5.png)

Below are the codes of the function for search and calling it in the podcastsList
1.search Function:
![sea](https://user-images.githubusercontent.com/70459251/165808735-3f292c21-d20b-42e7-8025-7173e9ddf6cd.png)
 
2. calling the function in Podcastslist:
![call f](https://user-images.githubusercontent.com/70459251/165809304-b9956eac-dfd2-401b-9069-33c158606f04.png)

When online trying to get health got one but don't know how to go about it as the mention react hooks and redux which i don't know how to use them. this is the link:
https://stackoverflow.com/questions/70523652/how-to-filter-or-search-for-services-in-another-component-react

**Comment by godsakani** [comment]
Hello @elhmn , @Sanix-Darker , @yokwejuste 
![no result](https://user-images.githubusercontent.com/70459251/166929076-b0c21ccf-4e12-4755-9600-f8294c74e92a.png)
I get this blank screen after calling the variable from the search form

code below:
![search fxn](https://user-images.githubusercontent.com/70459251/166929591-1df81805-3d29-4a6e-89aa-3e034419a9ee.png)
Search function
![pod2](https://user-images.githubusercontent.com/70459251/166929669-fcc90c6f-ca41-47b6-8746-d461d8cff995.png)
calling the variable

code reference:

https://stackoverflow.com/questions/70523652/how-to-filter-or-search-for-services-in-another-component-react

**Comment by yokwejuste** [comment]
> Hello @elhmn , @Sanix-Darker , @yokwejuste ![no result](https://user-images.githubusercontent.com/70459251/166929076-b0c21ccf-4e12-4755-9600-f8294c74e92a.png) I get this blank screen after calling the variable from the search form
> 
> code below: ![search fxn](https://user-images.githubusercontent.com/70459251/166929591-1df81805-3d29-4a6e-89aa-3e034419a9ee.png) Search function ![pod2](https://user-images.githubusercontent.com/70459251/166929669-fcc90c6f-ca41-47b6-8746-d461d8cff995.png) calling the variable
> 
> code reference:
> 
> https://stackoverflow.com/questions/70523652/how-to-filter-or-search-for-services-in-another-component-react

Hey @godsakani ! as suggestion  for this blank screen, when working with react  try and get the [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) from the [Chrome Webstore](https://chrome.google.com/webstore/category/extensions)

**Comment by yokwejuste** [comment]
> > Hello @elhmn , @Sanix-Darker , @yokwejuste ![no result](https://user-images.githubusercontent.com/70459251/166929076-b0c21ccf-4e12-4755-9600-f8294c74e92a.png) I get this blank screen after calling the variable from the search form
> > code below: ![search fxn](https://user-images.githubusercontent.com/70459251/166929591-1df81805-3d29-4a6e-89aa-3e034419a9ee.png) Search function ![pod2](https://user-images.githubusercontent.com/70459251/166929669-fcc90c6f-ca41-47b6-8746-d461d8cff995.png) calling the variable
> > code reference:
> > https://stackoverflow.com/questions/70523652/how-to-filter-or-search-for-services-in-another-component-react
> 
> Hey @godsakani ! as suggestion for this blank screen, when working with react try and get the [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) from the [Chrome Webstore](https://chrome.google.com/webstore/category/extensions)

As for this blank screen ![](https://user-images.githubusercontent.com/70459251/166929591-1df81805-3d29-4a6e-89aa-3e034419a9ee.png) you're calling the function [`foundPodcast`](https://github.com/osscameroon/podcasts/pull/23/files#diff-ed014df4e92027e8a90657de2176ffae132fe72221f1274f3920e68cfe2f9c82R6) without a declaration and it's found in the main component, try getting the output from the console tab in the developer tools( Ctrl + Shift + i ) .

**Comment by yokwejuste** [comment]
> Hello @elhmn , @Sanix-Darker , @yokwejuste ![no result](https://user-images.githubusercontent.com/70459251/166929076-b0c21ccf-4e12-4755-9600-f8294c74e92a.png) I get this blank screen after calling the variable from the search form
> 
> code below: ![search fxn](https://user-images.githubusercontent.com/70459251/166929591-1df81805-3d29-4a6e-89aa-3e034419a9ee.png) Search function ![pod2](https://user-images.githubusercontent.com/70459251/166929669-fcc90c6f-ca41-47b6-8746-d461d8cff995.png) calling the variable
> 
> code reference:
> 
> https://stackoverflow.com/questions/70523652/how-to-filter-or-search-for-services-in-another-component-react

From the [stackvoverflow](https://stackoverflow.com/questions/70523652/how-to-filter-or-search-for-services-in-another-component-react) they're passing as argument to to the search filter a json encrypted file, can i have a look on your `found podcast function` ?

**Comment by godsakani** [comment]
> code below: ![search fxn](https://user-images.githubusercontent.com/70459251/166929591-1df81805-3d29-4a6e-89aa-3e034419a9ee.png) Search function ![pod2](https://user-images.githubusercontent.com/70459251/166929669-fcc90c6f-ca41-47b6-8746-d461d8cff995.png) calling the variable

@yokwejuste foundpodcast is in the first screen here the function

**Comment by yokwejuste** [comment]
> > code below: ![search fxn](https://user-images.githubusercontent.com/70459251/166929591-1df81805-3d29-4a6e-89aa-3e034419a9ee.png) Search function ![pod2](https://user-images.githubusercontent.com/70459251/166929669-fcc90c6f-ca41-47b6-8746-d461d8cff995.png) calling the variable
> 
> @yokwejuste foundpodcast is in the first screen here the function

Still on the blank screen? 

please send the output of the console tab from the developer's tools

**Comment by godsakani** [comment]
Hello @yokwejuste  new error
I declared the foundpodcasts as a constant variable and assign it to tracks_oss the array. 
it displays but when typing is not displaying but when you inspect something is going on in the background.

![new ERRo](https://user-images.githubusercontent.com/70459251/167077686-1fbad293-a2e3-40a2-9f61-0640daf75af8.png)

**Comment by yokwejuste** [comment]
> Hello @yokwejuste new error I declared the foundpodcasts as a constant variable and assign it to tracks_oss the array. it displays but when typing is not displaying but when you inspect something is going on in the background.
> 
> ![new ERRo](https://user-images.githubusercontent.com/70459251/167077686-1fbad293-a2e3-40a2-9f61-0640daf75af8.png)

I'm not sure understanding what is happening here, you said **Typing** where are you typing? In the search  bar?

**Comment by godsakani** [comment]
> > Hello @yokwejuste new error I declared the foundpodcasts as a constant variable and assign it to tracks_oss the array. it displays but when typing is not displaying but when you inspect something is going on in the background.
> > ![new ERRo](https://user-images.githubusercontent.com/70459251/167077686-1fbad293-a2e3-40a2-9f61-0640daf75af8.png)
> 
> I'm not sure understanding what is happening here, you said **Typing** where are you typing? In the search bar?

yes search bar

**Comment by yokwejuste** [comment]
> > > Hello @yokwejuste new error I declared the foundpodcasts as a constant variable and assign it to tracks_oss the array. it displays but when typing is not displaying but when you inspect something is going on in the background.
> > > ![new ERRo](https://user-images.githubusercontent.com/70459251/167077686-1fbad293-a2e3-40a2-9f61-0640daf75af8.png)
> > 
> > 
> > I'm not sure understanding what is happening here, you said **Typing** where are you typing? In the search bar?
> 
> yes search bar

What output are you getting? ?I mean in the console.

**Comment by godsakani** [comment]
> >

I don't see any output apart from that screen that is showing like that

**Comment by godsakani** [comment]
> >

I don't see any output apart from that screen that is showing like that

**Comment by godsakani** [comment]
Issues already fixed
