### ISSUE TITLE
Make the sort button actually work

### ISSUE THREAD

**Issue by godsakani** [osscameroon/podcasts#29]
Task:
Make sort button dynamic.

Description:
The sort button should sort the tracks according to date uploaded

how to implement it: check ort the site below
https://codedec.com/tutorials/how-to-do-sorting-in-react/

**Comment by yokwejuste** [comment]
Hey @godsakani this is issue has being treated if I'm not mistaken.

**Comment by godsakani** [comment]
> Hey @godsakani this is issue has being treated if I'm not mistaken.

Yes @yokwejuste  it is

**Comment by yokwejuste** [comment]
Can you close it ?

**Comment by godsakani** [comment]
Issue fixed
