### ISSUE TITLE
Create a Component for the podcast list item

### ISSUE THREAD

**Issue by godsakani** [osscameroon/podcasts#8]

**Comment by yokwejuste** [comment]
What is this one for? You made a ticket from the kanban an issue?

**Comment by godsakani** [comment]
Sanix said we should create ticket in each task we do. when is done we close the issue and move to the next one. 
Though is stressing and i don't see the need

**Comment by yokwejuste** [comment]
> Sanix said we should create ticket in each task we do. when is done we close the issue and move to the next one. Though is stressing and i don't see the need

seriously 😆

**Comment by godsakani** [comment]
> 

See na no me oh.
Will create the component and open pull request  hahahahha

**Comment by yokwejuste** [comment]
😄 waiting for to review

**Comment by yokwejuste** [comment]
@godsakani This closed issue is not correct, from what I can see the task hasn't been performed. The task from the title was to generate a list component for the podcasts which wasn't done. Please check everything and let's discuss before the issue and PR is closed or merged respectively.

**Comment by godsakani** [comment]
> @godsakani This closed issue is not correct, from what I can see the task hasn't been performed. The task from the title was to generate a list component for the podcasts which wasn't done. Please check everything and let's discuss before the issue and PR is closed or merged respectively.

No please . it was 
First to create a podcastlist component which i did
secondly was then add that static list which am currently doing it
